identifier: me.thebroz.bettervisualizer
name: Better Visualizer
description: Replaces the default visualizer with a more reactive one.
author: thebroz
repo: https://github.com/the-broz/better-visualizer
entry:
  "plugin.js":
    type: main